version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0-faststart
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=password
      - APP_USER=appuser
      - APP_USER_PASSWORD=AppUserPass123
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

  backend-api:
    container_name: backend-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User Id=appuser;Password=AppUserPass123;Data Source=oracle-db:1521/XEPDB1
      - JWT__Key=supersecrethkey_that_is_at_least_32_bytes_long!
      - JWT__Issuer=MyApiIssuer
      - JWT__Audience=MyApiAudience
    depends_on:
      - oracle-db
    restart: unless-stopped

volumes:
  oracle-data:
