version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0-faststart
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=password
      - APP_USER=appuser
      - APP_USER_PASSWORD=AppUserPass123
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data:
